dist: trusty
arch:
  - amd64
  - ppc64le
language: c
compiler:
  - gcc
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y automake gtk-doc-tools gnome-doc-utils libgpgme11 libgpgme11-dev gpgsm lcov libidn2-0-dev
install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov
  - lcov --version
  - /usr/bin/gpgme-config --version
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters
script:
  - ./autogen.sh --enable-coverage && make && make check
after_success:
  - coveralls --exclude examples --exclude gmime/charset-map.c --exclude gmime/gen-table.c --exclude tests --gcov-options '\-lp'
